# Generated by Django 4.2.3 on 2024-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(max_length=50),
        ),
    ]
