# Generated by Django 4.2.9 on 2024-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0003_todo_date_alter_todo_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("priority", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
