# Generated by Django 4.2.9 on 2024-02-05 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
