# Generated by Django 4.2.9 on 2024-02-07 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0003_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="img",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updated",
            new_name="updated_date",
        ),
    ]
